blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/pomaretta/pomaretta.com/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/pomaretta/pomaretta.com/blob/main/README.md
    about: Check the project documentation
